apiVersion: v1
kind: Service
metadata:
  name: golang-sample-service
spec:
  ports:
  - port: 8080
    targetPort: go-sample-port
    protocol: TCP
  selector:
    app: golang-sample
  type: NodePort

