apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-sample-deployment
spec:
  replicas:  3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: k8s-demo
        image: tiagotele/golangsample:2.0
        ports:
        - name: go-sample-port
          containerPort: 8080
